// Every bit of editable copy on the site, with its default wording.
// Owners change these in place (edit mode → tap the text); changes are
// stored in site.json under "text" and merged over these defaults.
export const TEXT_DEFAULTS = {
  "nav.announcement": "Live on Facebook every evening at 8 PM  ·  Free shipping over $150",
  "nav.shop": "Shop", "nav.live": "Live", "nav.about": "About", "nav.help": "Help", "nav.inquiries": "Inquiries",
  "nav.signIn": "Sign in", "nav.watchLive": "Watch live",

  "hero.title": "Wear the Celebration",
  "hero.subtitle": "Handpicked Indian ethnic & fusion wear, revealed live every evening. Join the live, claim what you love, and we'll set it aside just for you.",

  "trust.1.title": "New drops every evening", "trust.1.sub": "Fresh styles, live at 8 PM",
  "trust.2.title": "Selected with love", "trust.2.sub": "Every product handpicked",
  "trust.3.title": "Ships nationwide", "trust.3.sub": "Carefully packed for you",
  "trust.4.title": "Easy size help", "trust.4.sub": "Message us anytime",

  "heritage.title": "Woven with heritage, chosen with love",
  "heritage.body": "Every saree, lehenga, and kurti is handpicked for the way it drapes, shines, and carries a story — from Banarasi weaves and zari work to delicate chikankari and bandhani. It's tradition you can wear, shared with the warmth of a small family boutique.",
  "heritage.p1.title": "Handpicked", "heritage.p1.sub": "Every product chosen by hand",
  "heritage.p2.title": "Heritage fabrics", "heritage.p2.sub": "Weaves & handwork we cherish",
  "heritage.p3.title": "Live & personal", "heritage.p3.sub": "Shop with us each evening",

  "home.cta.title": "Be the first to shop the newest drops",
  "home.cta.body": "Join us live on Facebook each evening — claim what you love in the comments and we'll set it aside just for you.",

  "banner.collections.title": "The Collection",
  "banner.collections.subtitle": "Browse everything in the boutique. Tap a category to filter, then sort to find your favorite — new products drop on the live every evening.",
  "banner.live.title": "Live Every Evening",
  "banner.live.subtitle": "The boutique comes alive at 8 PM. Replay the latest lives below and shop straight from the video.",

  "about.heading": "Hi, I'm the heart behind Reet Collections",
  "about.p1": "What started as a love for beautiful Indian wear — and a habit of helping friends find the perfect outfit — slowly grew into something I never expected: a little boutique with a big, warm community around it.",
  "about.p2": "Every evening I go live, hold up the products I've handpicked, and chat with you about fit, fabric, and which colour suits you best. It's the part of my day I look forward to most. There are no warehouses here, no endless racks — just products I genuinely love and think you'll love too.",
  "about.quote": "“I want every woman who shops with me to feel a little more like herself when she puts the outfit on.”",
  "about.promise": "Every product is selected with love and care, just for you. We're honored to be a part of your style journey.",

  "footer.tagline": "Every product is selected with love and care, just for you. We're honored to be a part of your style journey.",
  "footer.tagline.deva": "स्नेह से चुना गया",
  "footer.newsletter.eyebrow": "Join the list",
  "footer.newsletter.title": "Get notified every time we go live",
  "footer.col.shop": "Shop", "footer.col.help": "Help", "footer.col.connect": "Connect",
  "footer.link.allProducts": "All Products", "footer.link.newIn": "New In",
  "footer.link.thisWeek": "This Week", "footer.link.onSale": "On Sale",
  "footer.link.faq": "FAQ", "footer.link.inquiries": "Inquiries",
  "footer.link.shipping": "Shipping & Returns", "footer.link.account": "Account & Wishlist",
  "footer.link.liveSchedule": "Live Schedule", "footer.link.ourStory": "Our Story",
  "footer.link.facebook": "Facebook →",
  "footer.copyright": "Reet Collections. All rights reserved.",
  "footer.link.privacy": "Privacy", "footer.link.terms": "Terms", "footer.link.shipping2": "Shipping & Returns",

  "search.placeholder": "Search kurtis, lehengas, colors…",
  "search.emptyHint": "Start typing to search the collection.",

  "sizeGuide.label": "Size guide", "sizeGuide.title": "Size Guide",
  "sizeGuide.note": "Measurements in inches. When between sizes, we suggest sizing up.",
  "sizeGuide.help": "Need help? Message us on the live and we'll guide you.",

  "newsletter.placeholder": "Your email address", "newsletter.cta": "Notify me",
  "newsletter.done": "You're on the list — we'll email you the moment we go live.",
  "newsletter.invalid": "Please enter a valid email.",
  "newsletter.error": "Something went wrong — please try again.",
  "newsletter.hint": "Get an email every time we go live. No spam, ever.",

  "cart.bagTitle": "Your Bag", "cart.emptyTitle": "Your bag is empty", "cart.startShopping": "Start shopping",
  "cart.almostFree.pre": "You're", "cart.almostFree.post": "away from free shipping",
  "cart.unlockedFree.pre": "You've unlocked", "cart.unlockedFree.bold": "free shipping",
  "cart.checkoutCta": "Checkout", "cart.continueShopping": "Continue shopping",

  "faq.eyebrow": "Help", "faq.title": "Frequently Asked Questions",
  "faq.subtitle": "Answers to the questions we get asked most about shopping with Reet Collections.",
  "faq.1.q": "How do I order?",
  "faq.1.a": "Browse the collection, choose your size, and add to cart — or claim a product live on Facebook each evening. Placing an order reserves those products, and we confirm everything with you personally before payment.",
  "faq.2.q": "How does live shopping work?",
  "faq.2.a": "We go live on Facebook most evenings at 8 PM to reveal new arrivals. Comment to claim a product during the live, and we'll hold it for you. Want a reminder? Add your email and we'll notify you when we go live.",
  "faq.3.q": "What sizes do you carry?",
  "faq.3.a": "Most products come in S–XXL. Each product page has a size guide with measurements. When you're between sizes, we suggest sizing up — and you can always message us for help.",
  "faq.4.q": "How much is shipping?",
  "faq.4.a": "Flat-rate shipping is $9, and it's free on orders over $150. Every order is packed with care.",
  "faq.5.q": "Do you accept returns?",
  "faq.5.a": "If something isn't right, reach out within 7 days of delivery and we'll make it right. Items should be unworn with tags attached.",
  "faq.6.q": "How do I pay?",
  "faq.6.a": "Nothing is charged online. Once you place an order we message you to confirm your total and arrange payment the way that suits you — exactly like on our lives.",
  "faq.7.q": "Still have a question?",
  "faq.7.a": "Anything not answered here can be sent to us from the Inquiries page — it goes straight to us and a real person replies, usually within a day. You can also message us on Facebook.",

  "checkout.thankYou.title": "Thank you!",
  "checkout.thankYou.body.pre": "Your order",
  "checkout.thankYou.body.mid": "has been received. We'll reach out at",
  "checkout.thankYou.body.post": "to confirm everything and arrange payment & delivery.",
  "checkout.thankYou.note": "Your products are reserved for you in the meantime — just like on the live.",
  "checkout.thankYou.continueShopping": "Continue shopping",
  "checkout.empty.title": "Your bag is empty",
  "checkout.empty.body": "Add a product or two before checking out.",
  "checkout.empty.browse": "Browse the collection",
  "checkout.title": "Checkout",
  "checkout.subtitle": "Reserve your products now — we confirm every order personally before payment.",
  "checkout.contactDelivery": "Contact & delivery",
  "checkout.paymentTitle": "How payment works",
  "checkout.paymentBody": "Placing this order reserves your products — nothing is charged online. We'll message you to confirm your total and arrange payment the way that suits you best, exactly like on our lives.",
  "checkout.placeOrder": "Place order",
  "checkout.placingOrder": "Placing your order…",
  "checkout.requiredHint": "Fields marked * are required.",
  "checkout.orderSummary": "Order summary",
  "checkout.subtotalLabel": "Subtotal", "checkout.shippingLabel": "Shipping",
  "checkout.freeLabel": "Free", "checkout.totalLabel": "Total",
  "checkout.footNote": "Free shipping on orders over $150 · Every product checked & packed with care",

  "product.selectSize": "Select size",
  "product.oneSizeOnly": "One size only — send us an inquiry or ask on the live if you need fit help.",
  "product.onlyLeft.pre": "Only", "product.onlyLeft.post": "left",
  "product.soldOut": "Sold out", "product.addToCart": "Add to cart", "product.buyNow": "Buy it now",
  "product.saved": "Saved to wishlist", "product.save": "Save to wishlist",
  "product.freeShipping": "Free shipping over $150 · Selected with love & care",
  "product.designCode": "Design code", "product.theDetails": "The details",
  "product.fabric": "Fabric", "product.color": "Color", "product.category": "Category",
  "product.youMayAlsoLove": "You may also love", "product.moreFromCollection": "More from this collection",
  "product.off": "off", "product.newArrival": "New arrival",
  "product.defaultDescription": "A handpicked product, selected with love and care.",

  "productCard.new": "New", "productCard.addToBag": "Add to bag",

  "category.eyebrow": "Find your style", "category.title": "Shop by Category", "category.shopNow": "Shop now",

  "occasion.deva": "अवसर", "occasion.title": "Shop by Occasion",
  "occasion.subtitle": "From the mandap to the everyday — products chosen for every occasion.",
  "occasion.explore": "Explore",

  "live.watchOnFacebook": "Watch on Facebook",
  "live.recent.eyebrow": "Most recent", "live.recent.title": "Our 3 Newest Lives",
  "live.howItWorks.eyebrow": "Easy as one, two, three", "live.howItWorks.title": "How live shopping works",
  "live.step.1.t": "Join the live",
  "live.step.1.d": "We go live every evening at 8 PM on Facebook. New products are revealed one by one.",
  "live.step.2.t": "Comment to claim",
  "live.step.2.d": "Love something? Comment the code and your size — we set it aside in your name, no scramble.",
  "live.step.3.t": "We hold it for you",
  "live.step.3.d": "We confirm over message, pack it with care, and ship it to your door.",
  "live.archive.eyebrow": "The archive", "live.archive.title": "More lives this month",
  "live.seeAllFacebook": "See all on Facebook", "live.watch": "Watch",
  "live.connect.eyebrow": "Stay connected", "live.connect.title": "Where to find us",
  "live.card.facebook.label": "Facebook", "live.card.facebook.handle": "@Reetcollections068",
  "live.card.facebook.sub": "Watch our lives",
  "live.card.social.label": "Instagram & WhatsApp", "live.card.social.value": "Coming soon",
  "live.card.social.sub": "Add handle & number",
  "live.card.schedule.label": "Live schedule", "live.card.schedule.value": "Every evening · 8 PM",
  "live.card.schedule.sub": "Weekend specials too",
  "live.shopCta.title": "Can't wait for the next live?",
  "live.shopCta.body": "Shop everything currently in the boutique right now.",
  "live.shopCta.cta": "Shop the collection",

  "home.complete.eyebrow": "The complete edit", "home.complete.title": "Four Outfits, Three Views Each",
  "home.newIn.eyebrow": "Just arrived", "home.newIn.title": "New In",
  "home.sale.eyebrow": "Limited-time prices", "home.sale.title": "On Sale Now",
  "home.thisWeek.eyebrow": "Featured this week", "home.thisWeek.title": "This Week's Collection",
  "home.under60.eyebrow": "Wallet-friendly", "home.under60.title": "Under $60",
  "home.lives.eyebrow": "Catch up", "home.lives.title": "Our Newest Lives",
  "home.cta.eyebrow": "Live every evening · 8 PM", "home.cta.watchLive": "Watch the live",

  "legal.privacy.eyebrow": "Legal", "legal.privacy.title": "Privacy Policy",
  "legal.privacy.section.collect": "What we collect", "legal.privacy.section.use": "How we use it",
  "legal.privacy.section.payments": "Payments", "legal.privacy.section.device": "On your device",
  "legal.privacy.section.choices": "Your choices",
  "legal.privacy.updated": "July 2026",
  "legal.privacy.whatWeCollect": "When you place an order, we collect your name, email, phone number, and delivery address — the details needed to get your order to you.\nIf you sign in with Google, we receive your name, email address, and profile photo from Google. We never see your Google password, and we never post anything on your behalf.\nIf you join our live-notification list, we store your email address.",
  "legal.privacy.howWeUse": "Only to run the shop: confirming and delivering your orders, answering your messages, and — if you've joined the list — letting you know when we go live. We don't sell or share your information with anyone, and we don't send marketing you didn't ask for.",
  "legal.privacy.payments": "We don't collect card details on this site. Payment is arranged personally with you after your order is confirmed.",
  "legal.privacy.onYourDevice": "Your shopping bag, wishlist, and recently-viewed products are stored in your own browser so they're waiting for you when you come back. Signing in uses a session cookie to keep you signed in.",
  "legal.privacy.yourChoices.pre": "Want your details or your email removed from our list? Just ask through the",
  "legal.privacy.yourChoices.link": "Inquiries page",
  "legal.privacy.yourChoices.post": "and we'll take care of it.",

  "legal.terms.eyebrow": "Legal", "legal.terms.title": "Terms of Service",
  "legal.terms.section.orders": "Orders", "legal.terms.section.pricing": "Pricing & availability",
  "legal.terms.section.photos": "Product photos & colors", "legal.terms.section.returns": "Returns",
  "legal.terms.section.account": "Your account", "legal.terms.section.contact": "Getting in touch",
  "legal.terms.updated": "July 2026",
  "legal.terms.orders": "Placing an order reserves your products — it isn't a charge. We confirm every order personally (total, sizes, delivery) before payment is arranged. If we can't reach you within a few days, we may release reserved products back to the shop.",
  "legal.terms.pricing": "Most of our products are one-of-a-kind or in very limited quantities, sourced one at a time. Occasionally something sells on a live and online at the same moment — if that happens with your order, we'll let you know right away and make it right.",
  "legal.terms.photos": "We photograph every product ourselves and describe it as honestly as we can. Screens vary, so colors — especially jewel tones and gold work — can look slightly different in person.",
  "legal.terms.returns.pre": "Our full policy lives on the", "legal.terms.returns.link": "Shipping & Returns", "legal.terms.returns.post": "page.",
  "legal.terms.account": "Signing in with Google is optional — it keeps your wishlist and order history in one place. Please use your own account and real contact details so we can reach you about your orders.",
  "legal.terms.contact.pre": "Anything unclear? We're a small family shop and a real person reads every message — reach us through the",
  "legal.terms.contact.link": "Inquiries page",

  "legal.shipping.eyebrow": "Help", "legal.shipping.title": "Shipping & Returns",
  "legal.shipping.section.shipping": "Shipping", "legal.shipping.section.returns": "Returns & exchanges",
  "legal.shipping.section.damaged": "Damaged or wrong items", "legal.shipping.section.questions": "Questions",
  "legal.shipping.updated": "July 2026",
  "legal.shipping.rate": "Flat-rate shipping is $9, and it's free on orders over $150.",
  "legal.shipping.packing": "Once your order is confirmed, we pack it within 1–3 business days and email you when it's on the way. Every product is checked and folded by hand before it ships.",
  "legal.shipping.returns": "If something isn't right, message us within 7 days of delivery and we'll make it right — exchange, store credit, or refund.",
  "legal.shipping.condition": "Items should be unworn and unwashed with tags attached. Clearance products are final sale and marked as such on the product page.",
  "legal.shipping.damaged": "If your order arrives damaged or isn't what you ordered, send us a photo within 48 hours of delivery and we'll sort it out right away — that one's on us, including shipping.",
  "legal.shipping.questions.pre": "Message us on", "legal.shipping.questions.fb": "Facebook",
  "legal.shipping.questions.mid": "or send us an", "legal.shipping.questions.link": "inquiry",
  "legal.shipping.questions.post": "— we're happy to help.",

  "account.welcomeTitle": "Welcome to Reet",
  "account.welcomeBody": "Sign in to keep your wishlist and orders together, on any device.",
  "account.comingSoon": "Sign-in is opening soon. You can still browse, add to your bag and place orders as a guest.",
  "account.questionsPre": "Questions?", "account.questionsLink": "Send us an inquiry.",
  "account.welcomeBackPre": "Welcome back,",
  "account.ownerDashboard": "Owner dashboard", "account.signOut": "Sign out",
  "account.profile": "Profile", "account.memberSince": "Member since",
  "account.savedProducts": "Saved products", "account.ordersLabel": "Orders",
  "account.yourWishlist": "Your Wishlist",
  "account.noSaved": "No saved products yet — tap the heart on anything you love.",
  "account.browseCollection": "Browse the collection",
  "account.orderHistory": "Order History",
  "account.orderHistorySub": "Every order you've placed, what it contains, and exactly where it is right now.",
  "account.noOrders": "No orders yet — when you place one, it'll appear here.",
  "account.recentlyViewed": "Recently Viewed",
  "account.continueFacebook": "Continue with Facebook",
  "account.orReetSignIn": "or the Reet sign-in",
  "account.emailPlaceholder": "Your email address",
  "account.sendCode": "Email me a sign-in code", "account.sending": "Sending…",
  "account.codeSentPre": "We emailed a 6-digit code to",
  "account.signInCta": "Sign in", "account.checking": "Checking…",
  "account.differentEmail": "Use a different email",
  "account.privacyNote": "We use your sign-in only to keep your wishlist and orders together — nothing is ever posted on your behalf.",

  "order.status.new": "Received", "order.status.confirmed": "Confirmed", "order.status.shipped": "Shipped",
  "order.status.delivered": "Delivered", "order.status.cancelled": "Cancelled",
  "order.note.new": "We've received your order and reserved these items for you. Nothing has been charged — we'll message you to confirm the details and arrange payment.",
  "order.note.confirmed": "Your order is confirmed. We're packing it by hand and will let you know as soon as it's on the way.",
  "order.note.shipped": "Your order is on its way to the address below. Delivery usually takes a few days.",
  "order.note.delivered": "This order was delivered. If anything isn't right, send us an inquiry within 7 days of delivery and we'll sort it out.",
  "order.note.cancelled": "This order was cancelled, so nothing is owed. If that looks wrong to you, send us an inquiry and we'll check.",
  "order.showDetails": "Show order details", "order.hideDetails": "Hide order details",
  "order.payment.label": "Payment", "order.payment.subtotalLabel": "Subtotal",
  "order.payment.shippingLabel": "Shipping", "order.payment.totalLabel": "Total",
  "order.payment.note": "Nothing is charged online — we arrange payment with you personally.",
  "order.delivery.label": "Delivering to", "order.yourNoteLabel": "Your note:",
  "order.askPre": "Something to ask about this order?", "order.askLink": "Send an inquiry", "order.askQuote": "— quote",
  "order.freeShipping": "free shipping", "order.freeShippingWord": "free",

  "inquiry.banner.eyebrow": "Inquiries", "inquiry.banner.title": "Send an Inquiry",
  "inquiry.banner.subtitle": "Questions about a product, your size, or an order? Send it here and a real person will reply — usually within a day.",
  "inquiry.channel.messenger.title": "Facebook Messenger",
  "inquiry.channel.messenger.desc": "Fastest for orders & sizing — we're on every evening",
  "inquiry.channel.facebook.title": "Facebook",
  "inquiry.channel.facebook.desc": "Watch the lives & browse new arrivals",
  "inquiry.channel.email.title": "Email",
  "inquiry.channel.email.desc": "Prefer your own inbox? Write to us directly",
  "inquiry.quickAnswers.title": "Looking for quick answers?",
  "inquiry.quickAnswers.pre": "Shipping times, sizing, returns and payment are all covered on our",
  "inquiry.quickAnswers.link": "Help page",
  "inquiry.sent.eyebrow": "Inquiry sent", "inquiry.sent.title": "Thank you — we have it",
  "inquiry.sent.refPre": "Your reference is",
  "inquiry.sent.emailedPre": "We've emailed a copy to",
  "inquiry.sent.emailedPost": "and we'll reply there, usually within a day.",
  "inquiry.sendAnother": "Send another inquiry",
  "inquiry.form.title": "Your inquiry",
  "inquiry.form.subtitle": "Sent straight to us from this page — you'll get a copy by email.",
  "inquiry.form.namePlaceholder": "Your name",
  "inquiry.form.emailPlaceholder": "Your email (so we can reply)",
  "inquiry.form.phonePlaceholder": "Phone (optional)",
  "inquiry.form.orderPlaceholder": "Order number (e.g. RC-123456)",
  "inquiry.form.messagePlaceholder": "How can we help?",
  "inquiry.form.sendInquiry": "Send inquiry", "inquiry.form.sending": "Sending…",
  "inquiry.form.privacyNote": "We use your details only to answer this inquiry — never for anything else.",

  "shop.filters": "Filters", "shop.clearAll": "Clear all",
  "shop.noMatches": "No products match those filters.", "shop.clearFilters": "Clear filters",
  "shop.sort": "Sort", "shop.filtersBtn": "Filters",
  "shop.inStockOnly": "In stock only", "shop.inStockChip": "In stock",
  "shop.product": "product", "shop.products": "products", "shop.showResults": "Show results",

  "banner.collections.eyebrow": "Shop",
  "banner.category.subtitle": "Hover any category to explore more, or tap to filter the products below.",
};

export function textOf(site, key) {
  return (site?.text && site.text[key]) || TEXT_DEFAULTS[key] || "";
}
